const cityStateObj = {
    Denver: 'Colorado',
    'Phoenix/Scottsdale': 'Arizona',
    'Las Vegas': 'Nevada',
    Atlanta: 'Georgia',
    Austin: 'Texas',
    Baltimore: 'Maryland',
    Boston: 'Massachusetts',
    Charleston: 'South Carolina',
    Charlotte: 'North Carolina',
    Chicago: 'Illinois',
    Cincinnati: 'Ohio',
    Cleveland: 'Ohio',
    Columbus: 'Ohio',
    Dallas: 'Texas',
    Detroit: 'Michigan',
    Houston: 'Texas',
    Indianapolis: 'Indiana',
    'Kansas City': 'Missouri',
    'Los Angeles': 'California',
    Miami: 'Florida',
    Milwaukee: 'Wisconsin',
    Nashville: 'Tennessee',
    'New Orleans': 'Louisiana',
    'New York City': 'New York',
    'Oakland/Berkley': 'California',
    Orlando: 'Florida',
    Philadelphia: 'Pittsburgh',
    Portland: 'Oregon',
    Providence: 'Rhode Island',
    'Salt Lake City': 'Utah',
    'San Antonio': 'Texas',
    'San Diego': 'California',
    'San Francisco': 'California',
    Savannah: 'Georgia',
    Seattle: 'Washington',
    'St. Louis': 'Missouri',
    'Washington, DC': 'District of Colombia'
};

// const cityArray = ['Denver', 'Phoenix/Scottsdale', 'Las Vegas', 'Atlanta', 'Austin', 'Baltimore', 'Boston', 'Charleston', 'Charlotte', 'Chicago', 'Cincinnati', 'Cleveland', 'Columbus', 'Dallas', 'Detroit', 'Houston', 'Indianapolis', 'Kansas City', 'Los Angeles', 'Miami', 'Milwaukee', 'Nashville', 'New Orleans', 'New York City', 'Oakland/Berkley', 'Orlando', 'Philadelphia', 'Portland', 'Providence', 'Salt Lake City', 'San Antonio', 'San Diego', 'San Francisco', 'Savannah', 'Seattle', 'St. Louis', 'Washington, DC'];